# Generated by Django 6.0 on 2025-12-22 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="category",
            field=models.CharField(default="top news", max_length=20),
        ),
        migrations.AddField(
            model_name="article",
            name="source",
            field=models.CharField(default="top news", max_length=20),
            preserve_default=False,
        ),
    ]
