# Generated by Django 6.0 on 2025-12-22 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0002_article_category_article_source"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="source",
            field=models.CharField(default="", max_length=20),
        ),
    ]
