# Generated by Django 6.0 on 2025-12-22 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0003_alter_article_source"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="source",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
