# Generated by Django 6.0 on 2025-12-22 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0004_alter_article_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="summary",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="article",
            name="category",
            field=models.CharField(default="General", max_length=100),
        ),
        migrations.AlterField(
            model_name="article",
            name="source",
            field=models.CharField(default="Unknown", max_length=100),
        ),
    ]
