# Generated by Django 6.0 on 2025-12-22 03:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0005_article_summary_alter_article_category_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="article",
            name="created_at",
        ),
        migrations.AddField(
            model_name="article",
            name="published_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
